language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - ./create_credentials.sh
script:
  - npm test
  - ./travis_script.sh
env:
  global:
    - secure: jNFpyPaVI5hN3KbBth/NfDuNI144L5bv/tf+SKveTMCiVZYc1dK5bks4hloekFuSBYGNGCoybK18NHgN2e5opzLO/Cm6Mw8bePFhMSiLTnilstoLb47UI38kYNqIyLWEs61HuNSxX4ITosOtpsmKruNldhMVjbw5/F37Oxuc9sE=
    - secure: R5D81qqb6Vh6vIJTQztMGZwlsvOfk2eU5KygWPIxo7IVO7O0C9CIlUJCIZvzRnlqqqGClhSRLmEtrlo6XLiH7AkeZUbej/q5wfqiWvb0gaPxFIUJJbr7YA2/f/mTCdF2PB1uAo16DDG0u1NydZ69b71zrO3ynoiY9w8lHioUHVA=
    - secure: Bz/yGKLo5OMTCJ966ckVUZMngaTvlaBUDYYFtC6Dl8wBdjyMPmIdNcfRF2lagG+rZGBnvwVFpxRjwsYLB63t5yoqn0l9OhF+zB52H/4GqqK1BSgYyQ2eHFM9yi4kIStco4xu9ZDI7j4pJ4n7wasgiMXZC4jkzISpQVdFCfaCg58=
notifications:
  hipchat:
    rooms:
      - secure: FkpSSQ+czjGpuAcLFlKUMmoKi6ZaSi7RBb7GElVQ+BxOsi1hnTjEmtMRCQowJnQkDXQwmehfsgEfhn4aU96OrYAYyDWNWYhpfgFK/oPTHPFff9OJK+WCwqVpAFMwqkVzLQpF64cBSl7bDx0CJrqw0jD4m/Tb4gFCYGDo09b8F1I=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: always
branches:
  only:
    - master
